website/home/urls.py
from django.urls import path
from .views import index, about_me, test, coming_soon
from django.shortcuts import redirect

urlpatterns = [
    path("", lambda request: redirect("home:index")),
    path("homepage/", index, name="index"),
    path("aboutme/", about_me, name="about_me"),
    path("test/", test, name="test"),
    path("comingsoon/", coming_soon, name="coming_soon")
]

app_name = "home"

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/home/models.py
from django.db import models
from django.urls import reverse

class ProjectTag(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "Project Tag"
        verbose_name_plural = "Project Tags"

class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=160)
    link = models.TextField()
    tags = models.ManyToManyField(ProjectTag, blank=True, related_name="project_tags")
    created_on = models.DateTimeField(auto_now_add=True)
    STATUS_CHOICES = [
        ('completed', 'Completed'),
        ('ongoing', 'Ongoing'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)

    def __str__(self):
            return self.title

    project_image = models.ImageField(upload_to='home/project_images/', blank=True, null=True)

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'
        ordering = ["-created_on"]

class Timeline(models.Model):
    year = models.CharField(max_length=5)
    month = models.CharField(max_length=10)
    timeline_title = models.CharField(max_length=80)
    timeline_description = models.CharField(max_length=160)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.timeline_title

    class Meta:
        verbose_name = 'Timeline'
        verbose_name_plural = 'Timelines'
        ordering = ["updated_on"]

website/home/views.py
from django.shortcuts import render
from .models import Project, ProjectTag, Timeline


def index(request):
    grouped_projects = Project.objects.all().order_by('-created_on')
    
    return render(request, "home/index.html", {
        'grouped_projects': grouped_projects
    })

def about_me(request):
    timeline_sections = Timeline.objects.all().order_by('-year').order_by('-updated_on')
    # Starts with highest year, then updated the latest
    return render(request, "home/about_me.html", {
        'timeline_sections': timeline_sections
    })

def test(request):
    return render(request, "home/test.html", {
        
    })

def coming_soon(request):
    return render(request, "home/coming_soon.html", {
        
    })

website/home/templates/home/about_me.html
{% extends "base.html" %}
{% load static %}
{% block title %}About Me{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'home/styles/home.css' %}">

{% endblock %}
{% block content %}
<!-- TODO:
-Include working history timeline (most likely organizations)
-->
<section class="introduction-section">
    <div class="introduction-pictures-container">
        <div class="introduction-pictures">
            <div class="chewie">
                <img class="chewie-picture" id="click-image-1" style="cursor: pointer;"
                 src="{% static 'images/about/chewie.svg' %}"
                 data-images='[
                    "{% static "images/about/chewie.svg" %}",
                    "{% static "images/about/biscuit.svg" %}",
                    "{% static "images/about/peanut.svg" %}"
                ]'>
            </div>
            <div class="marcus-about">
                <img class="marcus-about-picture" src="{% static 'images/about/marcus-about.svg' %}">
            </div>
            <div class="luna">
                <img class="luna-picture" id="click-image-2" style="cursor: pointer;" 
                src="{% static 'images/about/luna.svg' %}"
                data-images='[
                    "{% static "images/about/luna.svg" %}",
                    "{% static "images/about/raya.svg" %}"
                ]'>
            </div>
        </div>
    </div>
    <div class="write-up">
        <h2 class="write-up-header"><span>Hi again! I am Marcus</span></h2>
        <div class="write-up-text">
            <div>
                <p>
                    I am a Computer Science student at Ateneo de Manila University, 
                    aiming to explore careers that benefit people’s daily lives through 
                    building software. I am taking specialized studies in enterprise systems 
                    and financial management with the goal of building tools that automate the 
                    technical processes of industries.  
        
                </p>
            </div>
            <div>
                <p> 
                    As a student, I have strong leadership and management skills in tech projects, 
                    with strengths in communication, administrative duties, and technical expertise. 
                    Currently, I am undergoing an internship at AHEAD Educational Group as an IT & Web 
                    Maintenance Intern, further honing my technical skills in web development, using HTML, 
                    CSS, and Python Django. 
                </p>
            </div>
           <div>
                <p>
                    Outside of school, I enjoy outdoor activities, such as swimming and taking leisurely walks 
                    with my pets. I also like reading light novels, manga, manhwa, and any other form of literature 
                    during my free time.
                </p>
           </div>
        </div>
        <div class="resume-button">
            <a href="https://www.canva.com/design/DAGGZ91_xBo/tjNVUtT0PeNXNAmVBV8Mmg/view?utm_content=DAGGZ91_xBo&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=h8d7b289e6d"
            target="_blank" rel="noopener noreferrer" class="main-button">Check my Resume!</a>
        </div>
    </div>
</section>
<section class="timeline-section">
    <!-- TODO
    Make a django instance of a timeline, which includes:
        -Starting year of the position
        -Starting month of the position
        -Title name of role
        -Short description of the position

        -NOTE: Every succeeding iteration of a django instance alternates positions from the 
        left side of the timeline line to the right side of the timeline line
        
    
    Add in a timeline line that extends depending on the amount of instances in the timeline
        -4px width, height depending on the amount of django instance
    -->
    <div class="timeline-section-divider">
        <img class="divider" src="{% static 'images/divider.svg' %}">
        <h2 class="timeline-main-title">My Timeline</h2>
    </div>
    <br>
    <div class="timeline-container">
        {% for timeline_section in timeline_sections %}
            {% if forloop.counter|divisibleby:2 %}
            <div class="timeline-group">
                <div class="timeline-left">
                    <div class="timeline-dot-container">
                        <div class="timeline-dot"></div>
                    </div>               
                    <div class="timeline-date">
                        <h5 class="timeline-year">{{ timeline_section.year }}</h5>
                        <h5 class="timeline-month">{{ timeline_section.month }}</h5>
                    </div>
                </div>
                <div class="timeline-right">
                    <div class="timeline-description">
                        <h5 class="timeline-title">{{ timeline_section.timeline_title }}</h5>
                        <p class="timeline-text">{{ timeline_section.timeline_description }}</p>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="timeline-group">
                <div class="timeline-left">
                    <div class="timeline-dot-container">
                        <div class="timeline-dot"></div>
                    </div>
                    <div class="timeline-description">
                        <h5 class="timeline-title">{{ timeline_section.timeline_title }}</h5>
                        <p class="timeline-text">{{ timeline_section.timeline_description }}</p>
                    </div>
                </div>
                <div class="timeline-right">
                    <div class="timeline-date">
                        <h5 class="timeline-year">{{ timeline_section.year }}</h5>
                        <h5 class="timeline-month">{{ timeline_section.month }}</h5>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</section>
{% endblock %}

website/home/templates/home/coming_soon.html
{% extends "base.html" %}
{% load static %}
{% block title %}Coming Soon{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'home/styles/coming_soon.css' %}">
{% endblock %}
{% block content %}
<section class="coming-soon-section">
    <h3><span>Website page still in progress</span></h3>
    <h1>Coming Soon!</h1>
</section>
{% endblock %}

website/home/templates/home/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Marcus Esteban{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'home/styles/home.css' %}">
{% endblock %}
{% block content %}
<section class="hero-section">
    <div class="hero-picture">
        <img id="hero-profile" src="{% static 'images/hero-picture.svg' %}" alt="My picture!">
    </div>
    <div class="hero-text">
        <div id="text-block">
            <h3 class="alt-color" id="change-text" >print<span>("Hello, World. I am")</span></h3>
        </div>
        <h1 id="name"><span>Marcus Jet<wbr> Esteban</span></h1>
        <img class="divider" src="{% static 'images/divider.svg' %}">
        <p>A Filipino programmer currently taking Computer Science 
            at Ateneo de Manila University. </p>
        <a href="{% url 'home:coming_soon' %}" class="main-button">Let's collaborate</a>
    </div>
</section>
<section class="value-proposition-section">
    <div class="logo-carousel-container">
        <div class="logo-carousel-group">
            <div class="company-logos">
                <img class="gdsc-logo" src="{% static 'images/logos/gdsc-logo.svg' %}">
                <img class="misa-logo" src="{% static 'images/logos/misa.svg' %}">
                <img class="hinomoto-logo" src="{% static 'images/logos/hinomoto.svg' %}">
                <img class="lions-logo" src="{% static 'images/logos/lions.svg' %}">
                <img class="compsat-logo" src="{% static 'images/logos/compsat.svg' %}">
            </div>
            <div class="company-logos">
                <img class="gdsc-logo" src="{% static 'images/logos/gdsc-logo.svg' %}">
                <img class="misa-logo" src="{% static 'images/logos/misa.svg' %}">
                <img class="hinomoto-logo" src="{% static 'images/logos/hinomoto.svg' %}">
                <img class="lions-logo" src="{% static 'images/logos/lions.svg' %}">
                <img class="compsat-logo" src="{% static 'images/logos/compsat.svg' %}">
            </div>
            <div class="company-logos">
                <img class="gdsc-logo" src="{% static 'images/logos/gdsc-logo.svg' %}">
                <img class="misa-logo" src="{% static 'images/logos/misa.svg' %}">
                <img class="hinomoto-logo" src="{% static 'images/logos/hinomoto.svg' %}">
                <img class="lions-logo" src="{% static 'images/logos/lions.svg' %}">
                <img class="compsat-logo" src="{% static 'images/logos/compsat.svg' %}">
            </div>
        </div>
    </div>
    <div class="value-proposition animate">
        <div class="value-proposition-description">
            <a href="{% url 'home:about_me' %}" class="circular-button">Get to know me</a>
            <div class="value-proposition-text">
                <h2 class="heading">Building solutions through leadership</h2>
                <p class="alternate">From a strong project management and programming background, 
                    I am a dedicated student leader capable of handling technical 
                    and operational processes in diverse working environments. 
                </p>
            </div>
        </div>
    </div>
    <img class="divider" src="{% static 'images/divider.svg' %}">
</section>
<section class="projects-section">
    <img class="divider" src="{% static 'images/divider.svg' %}">
    <h2 class="heading">Projects</h2>
    {% for project in grouped_projects %}
        <div class="projects-container">
            <!-- TODO
            -Include tags for the project
            -Include general date of project -->
            <div class="projects-text">
                <h3 class="heading"> {{ project.title }}</h3>
                <div class="tags-container">
                    {% for tag in project.tags.all %}
                        <h6 class="tag">
                            {{ tag.name }}
                        </h6>
                    {% endfor %}
                </div>
                <p class="description"> {{ project.description }}</p>
                <a href="{{ project.link }}" {% if project.status == 'ongoing' %}
                disabled style="opacity: 0.5; cursor: not-allowed;"{% endif %} 
                class="button" target="_blank" rel="noopener noreferrer">
                Project Link
                </a>
            </div>
            <div class="projects-image">
                {% if project.project_image %}
                    <img src="{{ project.project_image.url }}" alt="Project Image">
                {% endif%}
            </div>
        </div>
    {% endfor %}
</section>
{% endblock %}

website/home/templates/home/test.html
{% extends "base.html" %}
{% load static %}
{% block title%}Test{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'home/styles/home.css' %}">
{% endblock %}
{% block content %}
<section class="testing-section">
<h1 class="title-test">Javascript Crash Course</h1>

<div class="container-test">
    <h5 class="item-test">item 1</h5>
    <h5 class="item-test">item 2</h5>
    <h5 class="item-test">item 3</h5>
    <h5 class="item-test">item 4</h5>
</div>
<div class="butones-container">
    <a class="main-button">click me</a>
</div>
</section>
{% endblock %}

{% block nav%}
<a>hahahahah</a>
{% endblock%}

{% block scripts %}
<script src="{% static 'home/scripts/test.js' %}"></script>
{% endblock %}

website/templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- note: deploy website on digital ocean -->
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        <link rel="icon" href="{% static 'images/logos/favicon/m.svg' %}">
        {% block head %}
        {% endblock %}
    </head>
    <body>
        <header>
            <nav>
                <div class="nav-buttons">
                    <a href="{% url 'home:index' %}">Home</a>
                    <a href="{% url 'home:about_me' %}">About</a>
                    <!-- <a href="{% url 'home:test' %}">Test</a> -->
                    <a href="{% url 'home:coming_soon' %}">Contact</a>
                </div>       
                <div class="nav-block-content">
                    {% block nav %}
                    {% endblock %}
                    <h2>m<span>je</span>.</h2>
                </div>
            </nav>
        </header>
        <main>
            <div class="hero-designs">
                <div id="stars"></div>
            </div>
            <div class="scroll-progress-bar"></div>
            {% block content %}
            {% endblock %}
            <div class="cursors">
                <div></div>
            </div>
        </main>
        <footer>
            <div class="footer-container">
                <h3 class="text-logo">m<span>je</span>.</h3>
                <div class="footer-grid-container">
                    <div class="details-container">
                        <div class="general-contacts-container">
                            <h4>General Info</h4>

                            <h4 class="text-alternate"><span>Rodriguez, Rizal, Philippines</span></h4>
                            <h4 class="text-alternate"><span>marcus17esteban@gmail.com</span></h4>
                            <!-- Includes name, address, email -->
                        </div>
                        <div class="socials-container">
                            <div class="socials-group">
                                <div>
                                    <a href="https://www.linkedin.com/in/marcusesteban/" target="_blank" 
                                    rel="noopener noreferrer"><img class="linkedin-logo" src="{% static 'images/logos/footer/linkedin.svg' %}"></a>
                                </div>
                                <div>
                                    <a href="https://github.com/MJmetrix?tab=repositories" target="_blank" 
                                    rel="noopener noreferrer"><img class="github-logo" 
                                    src="{% static 'images/logos/footer/github.svg' %}"></a>
                                </div>
                                <div>
                                    <a href="https://www.instagram.com/marcus_jet_esteban/" target="_blank" 
                                    rel="noopener noreferrer"><img class="instagram-logo" 
                                    src="{% static 'images/logos/footer/instagram.svg' %}"></a>
                                </div>
                                <div>
                                    <a href="https://www.facebook.com/marcusjet.esteban" target="_blank" 
                                    rel="noopener noreferrer"><img class="facebook-logo" 
                                    src="{% static 'images/logos/footer/facebook.svg' %}"></a>
                                </div>
                            </div>
                            <!-- Includes linkedIn, Github, Instagram, and Facebook -->
                        </div>
                    </div>
                    <div class="footer-explore-container">
                        <h4>Explore</h4>
                        <div class="footer-nav-buttons">
                            <div>
                                <a href="{% url 'home:index' %}">Home</a>
                            </div>
                            <div>
                                <a href="{% url 'home:about_me' %}">About</a>
                            </div>
                            <!-- <div>
                                <a href="{% url 'home:coming_soon' %}">Work</a>
                            </div> -->
                            <div>
                                <a href="{% url 'home:coming_soon' %}">Contact</a>
                            </div>
                        </div>
                    </div>
                </div>
               
                <div class="copyright-container">
                    <div class="copyright-left">
                        <h5 class="text-alternate">Made in Visual Studio Code using CSS, HTML, Python (Django), and JS.</h5>
                        <h5 class="text-alternate">Designed in Figma</h5>
                    </div>
                    <div class="copyright-right">
                        <h5 class="text-alternate">Marcus Jet Esteban @ 2025</h5>
                    </div>
                </div>
            </div>  
            <!-- TODO:
            -Add simple contact information
            -Add copyright notice
            -links to github and whatnot
            -general address -->
            <!-- Footer stuff goes here -->
        </footer>
        <script src="{% static 'scripts/base.js' %}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>